version: "3"
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.3.0/24

services:
  node:
    container_name: node
    restart: always
    build:
      context: "./context"
      dockerfile: Dockerfile
      args:
        UID: 506
        GID: 1
        # если у вас линукс укажите здесь UID своего пользователя
        # можно узнать командой id -u  и  id -g
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    networks:
      net:
        ipv4_address: 172.22.3.2
    ports:
      - 8000:8000
    command: ["node", "server.js"]
